travis:
  secure:
    BINSTAR_TOKEN: t17ikPWLXYfDYYrz15WwYGK5vW0+zQkCjq+AxaEDY1yrtkM1FB0QfYWbM4uAqXEyU1YDPUciHScLnY7UcvvbVc6+ycG5p20QJLkI+W8mXQqmbQIJLBcBeYNFPNKPpbKqniJW+7ACW49agVwpJq7FqKSOtngfAnJWVREA0Kz7ArT0DDGw5g0OgEPRFz6EvvkMaADf3l5CcWAMb0WHriNijIIuevVJ8I8MjDj/NOpnLYPmbQHgg3Y0fR3zmgAy/5z9bWi4d6HadGOLoc9YRolICbPZZy/0QJ4AyqPppS6JCUH8GtXxPTaaIV56URqxq7qcad5//T3wMOdiK78OnHQJ6jtr4sh77emDdD/3CiDdenSHbap4zWQBYbrSNWQ7OEkgZPpkPF5ljNslnpWvgyqCh96XwNqmg2TymUNNzlrHew1SQgyIWbgnNWv/0XSl93OhAvxMcOtXXZDDoahTa30l4aT+X3/v82g5ieakneapa8zZwp7J1vY4r+pXdXhJogy6YOrAwuXpLh3oGXjfG/d53vXIC9QHrG0Koof3hABnV0sqTA7ozwu/j/AGq2Ap7SytWVXd+PwjxILEpSzuN8R5M8I5lMAcoPMDkfzlSQIquRtlNbB/2qBCrKNzMC7j7aLJpbIbIhVkbl+hxMvaGlu56cQXAx2dIz61+WgHvOTK+/8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
bot:
  automerge: true
